apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: metrics
  annotations:
    kubernetes.io/service-account.name: metrics
    bootstrap.kcp.io/battery: metrics-viewer
