kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metrics-viewer
  namespace: default
  annotations:
    bootstrap.kcp.io/battery: metrics-viewer
subjects:
- kind: ServiceAccount
  name: metrics
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: metrics-viewer
  apiGroup: ""
