site_name: kcp Documentation
repo_url: https://github.com/kcp-dev/kcp
site_url: https://docs.kcp.io/kcp/

# Site content
docs_dir: '../../content/en'
# Where to generate
site_dir: '../../generated/branch/en'

theme:
  name: material
  language: en
  # Common files such as images, stylesheets, theme overrides
  custom_dir: '../../overrides/'
  features:
    # Enable navigation section index pages, so we don't see Concepts > Concepts
    - navigation.indexes
    # Enable a copy button in code blocks
    - content.code.copy
    # Enable annotations on specific lines in code blocks
    - content.code.annotate
  logo: logo.png
  favicon: favicons/favicon.ico

extra:
  # This is needed so certain links, such as the language switcher, include the correct version.
  git_version: !ENV [GITHUB_REF_NAME, 'main']
  version:
    # Enable mike for multi-version selection
    provider: mike
  # Configure supported languages
  alternate:
    - name: English
      link: en
      lang: en

plugins:
  # https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin
  # Greater control over how navigation links are shown
  - awesome-pages
  # Docs site search
  - search
  # Use Jinja macros in .md files
  - macros:
      # This is relative to the repo root
      include_dir: 'docs/overrides'
      # This is relative to docs_dir
      module_name: '../../main'
  # https://github.com/ncdc/mkdocs-modify-base-url
  # ncdc's small plugin to fix the base_url so the version selector works
  - modify-base-url:
      prefix: '../'

markdown_extensions:
  # Code block highlighting
  - pymdownx.highlight:
      # Allows linking directly to specific lines in code blocks
      anchor_linenums: true
  # Inline code block highlighting
  - pymdownx.inlinehilite
  # Lets you embed content from another file
  - pymdownx.snippets
  # Arbitrary nesting of code/content blocks inside each other
  - pymdownx.superfences
  # Enable note/warning/etc. callouts
  - admonition

# Our CSS
extra_css:
  - stylesheets/kcp.css

# Live reload if any of these change when running 'mkdocs serve'
watch:
  - mkdocs.yml
  - ../../content/en
  - ../../overrides
