name: Generate and push docs

on:
  push:
    branches:
      - main
    tags:
      - "v*"
    paths:
      - "cmd/**"
      - "docs/**"
      - "pkg/**"

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  generate-and-push:
    name: Generate and push docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install mkdocs-material mkdocs-awesome-pages-plugin mkdocs-macros-plugin mike
      - run: make generate-docs deploy-docs LOCAL=1
